version: '3.3'

services:
  murmur:
    image: akito13/murmur
    container_name: murmur
    ports:
      - published: 64738
        target: 64738
        protocol: tcp
        mode: host
      - published: 64738
        target: 64738
        protocol: udp
        mode: host
      # gRPC API Port
      - published: 6502
        target: 6502
        protocol: tcp
        mode: host
    volumes:
      # Change mountpoint (left part) to your needs.
      - './data:/data'
