version: '3.3'

services:
  murmur:
    image: akito13/murmur
    ports:
      - published: 64738
        target: 64738
        protocol: tcp
        mode: host
      - published: 64738
        target: 64738
        protocol: udp
        mode: host
      # gRPC API Port
      - published: 50051
        target: 50051
        protocol: tcp
        mode: host
    volumes:
      # Change mountpoint (left part) to your needs.
      - '/home/murmur/data:/data'